### ISSUE TITLE
No update on NotifyOfExternalUpdate

### ISSUE THREAD

**Issue by TheCrether** [dravenk/webthing-go#5]
I've been trying out your library and found it quite easy to get into, but I am not able to update a property after the fact, my guess is that it is the following commented line.
Was this by mistake?

https://github.com/dravenk/webthing-go/blob/1f2e99613f7f3f8c77235908ea2b9e0adc896991/value.go#L51

**Comment by dravenk** [comment]
Hi, @TheCrether 
Thank you for the feedbock. I had completed the full Rest API but not yet the WebSocket API. The NotifyOfExternalUpdate not completed yet. All passed tests can be viewed with `test.sh`. Or using https://github.com/WebThingsIO/webthing-tester

**Comment by dravenk** [comment]
> I am not able to update a property after the fact

If you using the RESTAPI you should use this way as below to update a property. If you still have questions you need to provide more information. Thanks. 

https://github.com/dravenk/webthing-go/blob/master/examples/single-thing/single-thing.go#L165
```
property := thing.Property("on")	
on := property.Get().(bool)
property.Set(!on)
```

**Comment by TheCrether** [comment]
Ohhh, I completely overread that part of the code, my bad! Thanks for the reply!

I think that the WebSocket API would be a very important feature and I'll make a Pull Request when I have time.
